services:
  guacd:
    image: guacamole/guacd:1.5.3
    restart: unless-stopped
    container_name: guacd
    healthcheck:
      test: ["CMD", "pgrep", "guacd"]
      interval: 10s
      timeout: 5s
      retries: 5

  guacamole:
    build:
      context: ./build
    container_name: guacamole
    restart: unless-stopped
    env_file: .env
    environment:
      GUACD_HOSTNAME: guacd
    ports:
      - "8080:8080"
    depends_on:
      guacd:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/guacamole/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s