name: Validate and publish image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-compose-lint:
    runs-on: ubuntu-latest
    name: Validate docker-compose and env.example

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy .env.example as .env
        run: cp .env.example .env

      - name: Validate docker-compose.yml syntax
        run: docker compose -f docker-compose.yml config

      - name: Validate required .env variables
        run: |
          REQUIRED_VARS=(
            MYSQL_DATABASE
            MYSQL_USER
            MYSQL_PASSWORD
          )

          MISSING=()
          for VAR in "${REQUIRED_VARS[@]}"; do
            if ! grep -q "^${VAR}=" .env; then
              MISSING+=("$VAR")
            fi
          done

          if [ "${#MISSING[@]}" -ne 0 ]; then
            echo "Missing required variables in .env:"
            printf ' - %s\n' "${MISSING[@]}"
            exit 1
          fi

  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: docker-compose-lint
    if: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: |
            jmeiracorbal/guaca-guaca:${{ steps.version.outputs.tag }}
            jmeiracorbal/guaca-guaca:latest